quarkus:
  http:
    port: 8080

  log:
    file:
      enable: true
      path: logs/app.log
    console:
      enable: true
    category:
      "io.quarkus.security": DEBUG
      "io.smallrye.jwt": DEBUG
      "io.smallrye.jwt.auth.principal": DEBUG
      "org.hibernate.SQL": DEBUG
      "org.hibernate.type.descriptor.sql.BasicBinder": TRACE

  swagger-ui:
    always-include: true
    path: "/q/swagger-ui"
    auth-url: "/auth/token"
    bearer-token-enabled: true

  datasource:
    db-kind: postgresql
    username: postgres
    password: mdsoln
    jdbc:
      url: jdbc:postgresql://68.183.158.185:5432/mydatabase
    # Connection pool settings
    jdbc-pool:
      min-size: 5
      max-size: 20
      initial-size: 5
      background-validation-interval: 2M
      acquisition-timeout: 5
      leak-detection-interval: 1M
    # Statement timeout settings
    jdbc-statement:
      timeout: 300

  hibernate-orm:
    database:
      generation: update
    # Configure statement batching for better performance
    jdbc:
      statement-batch-size: 20
    # Configure transaction timeout
    transaction:
      timeout: 600
    properties:
      hibernate:
        # Configure batch fetching
        default_batch_fetch_size: 20
        # Configure order inserts and updates
        order_inserts: true
        order_updates: true
        # Configure Envers
        envers:
          autoRegisterListeners: true
          revision_field_name: rev
          revision_type_field_name: revtype
          track_entities_changed_in_revision: true
          global_with_modified_flag: true
          store_data_at_delete: true
          # Configure audit strategy
          audit_strategy: org.hibernate.envers.strategy.DefaultAuditStrategy

  smallrye-json:
    date-format: "yyyy-MM-dd'T'HH:mm:ss"

  arc:
    remove-unused-beans: false

mp:
  jwt:
    verify:
      issuer: http://68.183.158.185:8080/auth
    groups:
      path: groups  # this is for roles, but leave it here if you are using roles as well
    path:
      permissions: permissions  # this maps the "permissions" claim

smallrye:
  jwt:
    sign:
      key:
        location: privateKey.pem
    verify:
      key:
        location: publicKey.pem
    always-check-authorization: true
    path:
      permissions: permissions  # Ensure this maps to the permissions claim in your JWT
